### ISSUE TITLE
flip a subset of the matrix before clustering rows 

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/EnrichedHeatmap#30]
Hi Zuguang,

I always learn something new from your write-ups. I was reading https://bioconductor.org/packages/release/bioc/vignettes/EnrichedHeatmap/inst/doc/row_odering.html

It is very nice to have closeness distance for clustering. 

Fig1 of this paper http://m.genome.cshlp.org/content/22/9/1735.full

<img width="456" alt="screenshot 2018-06-28 14 58 08" src="https://user-images.githubusercontent.com/4106146/42057682-bff05e1c-7ae3-11e8-9b38-9fb5153c9001.png">

is doing something similar, but flips subset of the matrix if the strandness of the feature is not important. e.g. a binding site of TF.  for TSSs, the strandness is important.

I hope it is not too much work to add this functionality.

one has to define the cluster first, EnrichedHeatmap uses the complete method to cluster. so, one can use `cutree` to define the number of clusters (or specify how many clusters one wants), and then flip the symmetric signals and then merge the clusters.

I am not sure if I have made myself clear, but your tools are all very awesome!

Thanks!
Tommy

**Comment by jokergoo** [comment]
Thanks Tommy! The closeness distance proposed in my paper is kind of a try to capture the patterns of the closeness of regions. It works, however I would say it is not an efficient way for doing it. I will read the paper you attached!

**Comment by crazyhottommy** [comment]
the code in the paper was written in matlab, I only know R...I want an R version of something similar. look forward to reading your paper!

**Comment by jokergoo** [comment]
I finally have time to look at this comment. I quickly went through the method of this CAGT tool. For me, the algorithm basically contains two steps:

1. PAM partitioning on the normalized matrix with a large initial number of groups k
2. merging groups interatively with or without flip the matrix by the anchor targets.

For the first point, I think choosing optimized number of groups is a common problem for clustering and there is no perfect solution for this. And for the second point, I think it is worth to implement it in EnrichedHeatmap because it is true that only the relative distance to targets is important while whether it is on the upstream or downstream is of no importance.

**Comment by jokergoo** [comment]
I've added a `flip_upstream` argument to `normalizeToMatrix()`. The process is basically:

1. normalize to the matrix with distinguishing upstream and downstream
2. flip the upstream part and add to the downstream

![test](https://user-images.githubusercontent.com/449218/48349014-4c4cb580-e683-11e8-99fd-07590db6c63f.png)

**Comment by crazyhottommy** [comment]
Thanks will take a look and close it for now!
