### ISSUE TITLE
top_annotation Error in unit(values, units, data = data) :    'x' and 'units' must have length > 0

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/EnrichedHeatmap#32]
Hi Zuguang,

After upgrading to the latest in github, my previous code is not working
for plotting chromatin state categorical matrix:
This is fine
```r
EnrichedHeatmap(mat_states_Rpre[ids,], name = "states_Rpre", col = states_col,
    column_title = "States Rpre", use_raster =T, raster_quality = 5)
```

This gives me error after adding top_annotation
```
Error in unit(values, units, data = data) : 
  'x' and 'units' must have length > 0
```
```r
EnrichedHeatmap(mat_states_Rpre[ids,], name = "states_Rpre", col = states_col,
    column_title = "States Rpre", use_raster =T, raster_quality = 5,
    top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(lty = 1:2), 
                                                              ylim = c(0,1)),annotation_height = 0.5))
```
Anything changed?

Thx!
Tommy

**Comment by jokergoo** [comment]
What if you remove `annotation_height = 0.5`? 

Have you also updated EnrichedHeatmap? I think now if you want to set the height of the top annotation, you need to do like:

```{r}
anno_enriched(..., height = unit(3, "cm"))
```

or

```{r}
HeatmapAnnotation(..., annotation_height = unit(3, "cm"))
```

**Comment by crazyhottommy** [comment]
```r
anno_enriched(..., height = unit(3, "cm"))
```
worked fine.


```r
HeatmapAnnotation(..., annotation_height = unit(3, "cm"))
```
gives me the same error

```
Error in unit(values, units, data = data) : 
  'x' and 'units' must have length > 0
```

**Comment by jokergoo** [comment]
Ah. It is a bug when `annotation_height` is set with only one annotation in `HeatmapAnnotation()`. I've just fixed in the ComplexHeatmap package.

**Comment by jokergoo** [comment]
Also, for your example, you cannot set `annotation_height` as one single numeric value because `annotation_height` corresponds to the height of every single annotation in `HeatmapAnnotation()`.

`annotation_height` can be set as a vector of numeric values which correspond to the relative fraction of every single annotation in the global heatmap annotation; or a vector of units.

In the new version of ComplexHeatmap, the preferable way is to directly set `height` in `anno_*()` functions.

**Comment by crazyhottommy** [comment]
thanks @jokergoo for the extra info.  closing it now.
