### ISSUE TITLE
Use my own matrix instead of `normalizeToMatrix`

### ISSUE THREAD

**Issue by AlicePsyche** [jokergoo/EnrichedHeatmap#9]
Hi, 

In your documentation, you say 
> actually mat1 is just a normal matrix with several additional attributes

Could I use my own matrix instead of file generated by `normalizeToMatrix` ?  I already have multiple sample matrixes and I really like your heatmap `concatenate` function. Do I have to do the coverage in R again? 

Thanks in advance !

**Comment by jokergoo** [comment]
What is your "mulitple sample matrix" about? Is it kind like expression matrix? For the matrix returned by `normalizeToMatrix()`, columns do not correspond to samples, while instead, they correspond to positions to certain genomic targets (e.g. TSS). If your matrix is just a normal "expression-like" matrix, you can directly use the `Heatmap()` function and heatmaps can be concatenated to other heatmaps.

**Comment by AlicePsyche** [comment]
I have one matrix for one sample with binned values( windows around TSS)

```
#genes:16380
#downstream:2500        upstream:2500   body:0  bin size:20
2.32 2.32 0.77 0.77 0.77 0.77 0.77 0.77 0.77 0.77 0.77 0.77 ...
```

Actually, it was generated by `computeMatrix` function from deeptools but their plot function can't cater for my needs.

**Comment by jokergoo** [comment]
You need to add several attributes to the matrix. These attributes are:

- `upstream_index`: a vector of index of columns which correspond to upstream. In your case, it should be:

```{r}
attr(mat, "upstream_index") = 1:(2500/20)
```

- `target_index`: a vector of index of columns which correspond to target body. In your case, it should be:

```{r}
attr(mat, "upstream_index") = integer(0)
```

- `downstrean_index`: a vector of index of columns which correspond to the downstream. In your case, it should be:

```{r}
attr(mat, "downstream_index") = 1:(2500/20) + 2500/20
```

- `extend`: a vector of length two which correspond to the extension to upstream and downstream:

```{r}
attr(mat, "extend") = c(2500, 2500)
```

- `smooth`: whether signals are removed. I think it should be `FALSE` here? Not important for making the heatmap

```{r}
attr(mat, "smooth") = FALSE
```

- `signal_name`: not very important, but still you should better give it a name

```{r}
attr(mat, "signal_name") = "something"
```

- `target_name`: not very important neither

```{r}
attr(mat, "target_name") = "something"
```

- `target_is_single_point`: not very important, in your case, it should be `TRUE` (because target is tss)

```{r}
attr(mat, "target_is_single_point") = TRUE
```

- `empty_value`: what is the value for those bins where there is no signal overlapped. I guess it is zero?

```{r}
attr(mat, "empty_value") = 0
```

- `class`: add `normalizedMatrix` to the class attributes:

```{r}
class(mat) = c("normalizedMatrix", "matrix")
```

If everything is correctly set, when you enter `mat`, something like following will show:

```{r}
> mat
Normalize something to something:
  Upstream 2500 bp (125 windows)
  Downstream 2500 bp (125 windows)
  Not include target regions
  16380 signal regions
```

**Comment by AlicePsyche** [comment]
Sorry for the late update... It worked ! Thanks a lot.

**Comment by jokergoo** [comment]
That is great! I have never tested to manually assign these attributes to a matrix which was generated by other tool.

**Comment by sda910722** [comment]
EnrichedHeatmap is a great tool!
But I also want to use my own matrix instead of file generated by normalizeToMatrix.
Of course, I followed your suggestions as above, but it didn't work for me.

I have one matrix for 508 H3K4me1 peaks with binned values for plotting EnrichedHeatmap (upstream:1000, downstream:1000, bin size:10, windows are around midpoint).

The matrix was generated by computeMatrix function from deeptools.
And I set the colnames of the matrix as "u1, u2, ... u100, d1, d2, ... d100"

Thus, the matrix is like that:
```
> dim(mat)
[1] 508 200
```
![image](https://user-images.githubusercontent.com/27658052/40212974-8cd06f96-5a85-11e8-91c1-3836900e729c.png)
But after all things done, I got a strange data which showed "Downstream 1000 bp, but 0 windows"
```
> mat
Normalize H3K4me1 RPKM to H3K4me1:
  Upstream 1000 bp (100 windows)
  Downstream 1000 bp (0 windows)
  Include target regions (width = 1)
   target region
```

And the EnrichedHeatmap function told me that the data should be generated by normalizeToMatrix.

```
> EnrichedHeatmap(mat)
Error in EnrichedHeatmap(mat) : 
  `mat` should be generated by `normalizeToMatrix()`.
```
I also tried using the converted numeric vector (length: 101,600) instead of matrix (508x200), but the result was the same. 

I have no idea now. Would you like to help me out?

**Comment by jokergoo** [comment]
I guess you might miss something. Can you also attach the code you adjust the matrix?

**Comment by sda910722** [comment]
Thank you for your reply.
As github only accepted compressed file in zip format, so I compressed the data and code I used.
The compressed file data.code.zip, contains two files:
The mat.RData for the matrix, and conv2EnrichedHeatmap.R for the code.

[data.code.zip](https://github.com/jokergoo/EnrichedHeatmap/files/2015646/data.code.zip)

**Comment by sda910722** [comment]
Dear Zuguang,
Thank you for your reply.
Here is the data and code I used.
The mat.RData contains the matrix,
and conv2EnrichedHeatmap.R contains the code.

I also published them in github.
Best wishes.
Guanxiong

2018-05-18 11:55 GMT+08:00 Zuguang Gu <notifications@github.com>:

**Comment by sda910722** [comment]
Sorry for my carelessness. After correcting the typo, it works.
I also try to use the function "as.normalizedMatrix()" in the latest package installed using 'devtools::install_github("jokergoo/EnrichedHeatmap")'.
But I got an error:
```
>   mat2 = as.normalizedMatrix(mat, k_upstream = 100, k_downstream = 100, extend = 1000, signal_name= "H3K4me1 RPKM", target_name="H3K4me1")
Error in as.normalizedMatrix(mat, k_upstream = 100, k_downstream = 100,  : 
  object 'target_is_single_point' not found

```
In your code, I found a block of "if(){}", I thought the object "target_is_single_point" was not defined.

```
 if (!target_is_single_point) {
        colnames(mat) = c(.paste0("u", seq_along(upstream_index)), 
            .paste0("t", seq_along(target_index)), .paste0("d", 
                seq_along(downstream_index)))
    }
```
This function will be very useful and convenient. At last, EnrichedHeatmap is a great tool.
Best wishes
Guanxiong
